In [5]:
import pandas as pd

df = pd.read_csv("../data/raw/open_meteo/meteorology.csv")
print(df.shape)
print(df["provincia"].unique())
df.head(10)

(210240, 7)
<StringArray>
[   'Cádiz',   'Burgos',  'Navarra', 'Zaragoza',     'Lugo', 'A Coruña',
 'Albacete',    'Soria']
Length: 8, dtype: str

,time,wind_direction_100m,pressure_msl,wind_speed_100m,temperature_2m,wind_gusts_10m,provincia
0,2021-01-01T00:00,294,1017.8,7.75,12.6,8.2,Cádiz
1,2021-01-01T01:00,288,1017.4,7.97,12.5,8.5,Cádiz
2,2021-01-01T02:00,292,1016.9,9.15,12.8,11.6,Cádiz
3,2021-01-01T03:00,303,1016.4,8.68,12.3,12.0,Cádiz
4,2021-01-01T04:00,308,1016.4,8.12,11.8,10.3,Cádiz
5,2021-01-01T05:00,319,1016.2,8.79,11.9,10.3,Cádiz
6,2021-01-01T06:00,320,1016.0,7.73,11.3,10.4,Cádiz
7,2021-01-01T07:00,325,1015.7,8.41,10.7,9.4,Cádiz
8,2021-01-01T08:00,310,1015.4,8.17,10.4,9.6,Cádiz
9,2021-01-01T09:00,319,1016.2,9.28,10.4,10.7,Cádiz

In [6]:
df_esios = pd.read_csv("../data/raw/esios/generacion_eolica.csv")
print(df_esios.shape)
print(df_esios["geo_name"].unique())
df_esios.head(10)

(210407, 4)
<StringArray>
[   'Cádiz',   'Burgos',  'Navarra', 'Zaragoza',     'Lugo', 'A Coruña',
 'Albacete',    'Soria']
Length: 8, dtype: str

      value                       datetime  geo_id  geo_name
0   405.441  2021-01-01T01:00:00.000+01:00      23     Cádiz
1   172.828  2021-01-01T01:00:00.000+01:00      29    Burgos
2   257.001  2021-01-01T01:00:00.000+01:00      32   Navarra
3   701.630  2021-01-01T01:00:00.000+01:00      39  Zaragoza
4   169.458  2021-01-01T01:00:00.000+01:00      43      Lugo
5   178.036  2021-01-01T01:00:00.000+01:00      50  A Coruña
6  1153.043  2021-01-01T01:00:00.000+01:00      57  Albacete
7    99.016  2021-01-01T01:00:00.000+01:00      64     Soria
8   471.684  2021-01-01T02:00:00.000+01:00      23     Cádiz
9   206.301  2021-01-01T02:00:00.000+01:00      29    Burgos